-- Study Group Finder MySQL schema
-- Run this entire script in MySQL Workbench.

CREATE DATABASE IF NOT EXISTS study_group_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE study_group_db;

CREATE TABLE IF NOT EXISTS Users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  program VARCHAR(255),
  year INT,
  role VARCHAR(50) NOT NULL DEFAULT 'student',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Groups (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  course VARCHAR(255),
  faculty VARCHAR(255),
  description TEXT,
  location VARCHAR(255),
  userId INT UNSIGNED,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_groups_userId (userId),
  CONSTRAINT fk_groups_user
    FOREIGN KEY (userId) REFERENCES Users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Sessions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  groupId INT UNSIGNED NOT NULL,
  date DATETIME,
  time VARCHAR(255),
  location VARCHAR(255),
  description TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sessions_groupId (groupId),
  CONSTRAINT fk_sessions_group
    FOREIGN KEY (groupId) REFERENCES Groups(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Favorites (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  userId INT UNSIGNED NOT NULL,
  groupId INT UNSIGNED NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_favorites_user_group (userId, groupId),
  KEY idx_favorites_groupId (groupId),
  CONSTRAINT fk_favorites_user
    FOREIGN KEY (userId) REFERENCES Users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_favorites_group
    FOREIGN KEY (groupId) REFERENCES Groups(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  groupId INT UNSIGNED NOT NULL,
  userId INT UNSIGNED NOT NULL,
  content TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_posts_groupId (groupId),
  KEY idx_posts_userId (userId),
  CONSTRAINT fk_posts_group
    FOREIGN KEY (groupId) REFERENCES Groups(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_posts_user
    FOREIGN KEY (userId) REFERENCES Users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS GroupMembers (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  groupId INT UNSIGNED NOT NULL,
  userId INT UNSIGNED NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_group_members_user_group (groupId, userId),
  KEY idx_group_members_userId (userId),
  CONSTRAINT fk_group_members_group
    FOREIGN KEY (groupId) REFERENCES Groups(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_group_members_user
    FOREIGN KEY (userId) REFERENCES Users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Invitations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  groupId INT UNSIGNED NOT NULL,
  inviterId INT UNSIGNED NOT NULL,
  inviteeId INT UNSIGNED NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_invitations_group_invitee (groupId, inviteeId),
  KEY idx_invitations_groupId (groupId),
  KEY idx_invitations_inviteeId (inviteeId),
  CONSTRAINT fk_invitations_group
    FOREIGN KEY (groupId) REFERENCES Groups(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_invitations_inviter
    FOREIGN KEY (inviterId) REFERENCES Users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_invitations_invitee
    FOREIGN KEY (inviteeId) REFERENCES Users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;
